# Configuration file for RS-M90E7 Joint 6
vendor_id: 0x000001DD
product_id: 0x10306086
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: false 
auto_state_transitions: false

sdo:  # sdo data to be transferred at drive startup
  - {index: 0x6060, sub_index: 0, type: int8, value: 0}
  
rpdo:  # RxPDO
  - index: 0x1601
    channels:
      # Control Word
      - {index: 0x6040, sub_index: 0, type: uint16, command_interface: control_word, default: 128} 
      # Target Position (一圈5100000) -> 5100000/(2*π) = 811690.209768666
      - {index: 0x607a, sub_index: 0, type: int32, command_interface: "position", default: .nan, factor: 811690.209768666} 
      # Target Velocity
      - {index: 0x60FF, sub_index: 0, type: int32, default: 0} 
      # Target Torque
      - {index: 0x6071, sub_index: 0, type: int16, default: 0, command_interface: "effort"} 
      # Mode of Operation
      - {index: 0x6060, sub_index: 0, type: int8, default: .nan, command_interface: "operation_mode"} 

tpdo:  # TxPDO
  - index: 0x1a01
    channels:
      # Status Word
      - {index: 0x6041, sub_index: 0, type: uint16, state_interface: "status_word"} 
      # Actual Position (一圈5100000) -> 2π/5100000 = 0.000001232
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: "position", factor: 0.000001232} 
      # Actual velocity
      - {index: 0x606c, sub_index: 0, type: int32, state_interface: "velocity"} 
      # Actual Torque
      - {index: 0x6077, sub_index: 0, type: int16, state_interface: "effort"}
      # Mode of operation display
      - {index: 0x6061, sub_index: 0, type: int8, state_interface: "operation_mode"} 

sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: disable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}